### ISSUE TITLE
Change to Haiku Layoutmanagement

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Paradoxianer/projectconceptor_old#3]
```
This should make it much more lightweight (should make Toolbar and diver 
implementation obsolet)
```

Original issue reported on code.google.com by `two4...@gmail.com` on 28 Dec 2013 at 5:55

**Comment by Paradoxianer** [comment]
This issue was moved to Paradoxianer/ProjectConceptor_base#6

**Comment by Paradoxianer** [comment]
This issue was moved to Paradoxianer/ProjectConceptor_base#8
