### ISSUE TITLE
Fix Freemind Translator

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Paradoxianer/projectconceptor_old#4]
```
Freemindtranslator not fully supported :(
```

Original issue reported on code.google.com by `two4...@gmail.com` on 28 Dec 2013 at 5:57

**Comment by Paradoxianer** [comment]
This issue was moved to Paradoxianer/ProjectConceptor_base#7

**Comment by Paradoxianer** [comment]
This issue was moved to Paradoxianer/ProjectConceptor_base#9
