### ISSUE TITLE
Redesign Code Return a ShortCutFilter 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Paradoxianer/projectconceptor_old#8]
```
Wich will be added to the BWindow on activate and removed on deactive
```

Original issue reported on code.google.com by `two4...@gmail.com` on 28 Dec 2013 at 6:08
- Blocking: #5

**Comment by Paradoxianer** [comment]
This issue was moved to Paradoxianer/ProjectConceptor_base#13
